* Plus Minus

Given an array of integers, calculate the ratios of its elements that are positive, negative, and zero.

Print the decimal value of each fraction on a new line with 6 places after the decimal.

Note: This challenge introduces precision problems. The test cases are scaled to six decimal places, though answers with absolute error of up to 10 ^ -4  are acceptable.

Example
#+begin_src 
arr = [ 1, 1, 0, -1, -1 ]
#+end_src

There are n=5 elements, two positive, two negative and one zero. Their ratios are 2/5, 2/5 and 1/5. Results are printed as:

#+begin_src 
0.400000
0.400000
0.200000
#+end_src

* Function Description

Complete the plusMinus function in the editor below.

plusMinus has the following parameter(s):

    int arr[n]: an array of integers

* Print

Print the ratios of positive, negative and zero values in the array. Each value should be printed on a separate line with

digits after the decimal. The function should not return a value.

* Input Format

The first line contains an integer, n, the size of the array.
The second line contains space-separated integers that describe arr[n].

* Constraints

#+begin_src 
0 < n =< 100
-100 =< arr[i] =< 100
#+end_src

* Output Format

Print the following 3 lines, each rounded to 6 decimals:

    proportion of positive values
    proportion of negative values
    proportion of zeros

* Sample Input

#+begin_src 
STDIN           Function
-----           --------
6               arr[] size n = 6
-4 3 -9 0 4 1   arr = [-4, 3, -9, 0, 4, 1]
#+end_src

* Sample Output

#+begin_src 
0.500000
0.333333
0.166667
#+end_src

* Explanation

There are 3 positive numbers, 2 negative numbers, and 1 zero in the array.
The proportions of occurrence are positive:3/6 , negative: 2/6 and zeros: 1/6.

* Solution

See [[file:Main.scala]] for the implementation. Run it with:

#+begin_src shell
  scala-cli Main.scala
#+end_src